---

- name: Install clamav
  apt:
    name: clamav
    state: present

- name: Install clamav daemon
  apt:
    name: clamav-daemon
    state: present
 
- name: Install cpulimit for clamav 
  apt:
    name: cpulimit
    state: present

- name: "stop clamav-freshclam"
  systemd:
      name: clamav-freshclam
      state: stopped 

- name: "run freshclam to update antivirus signatures"
  shell: freshclam
  ignore_errors: yes 
  
- name: "start clamav-freshclam"
  systemd:
      name: clamav-freshclam
      state: started

- name: 'enable clam-av as a service'
  systemd:
    name: clamav-freshclam
    enabled: yes 
  